In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as spst

#import sys
#sys.path.insert(sys.path.index('')+1, 'D:/Github/pyfeng')
import pyfeng as pf

np.set_printoptions(precision=3)

# Uncorrelated Heston Model Approximation by Ball & Roma (1994)


Ball CA, Roma A (1994) Stochastic Volatility Option Pricing. Journal of Financial and Quantitative Analysis 29:589–607. https://doi.org/10.2307/2331111

In [3]:
pf.HestonFft.init_benchmark()

sigma   theta     vov     rho      mr   texp  spot    intr  divr  \
Sheet                                                                        
1      0.040000  0.0400  1.0000 -0.9000  0.5000  10.00   100  0.0000  0.00   
2      0.040000  0.0400  0.9000 -0.5000  0.3000  15.00   100  0.0000  0.00   
3      0.090000  0.0900  1.0000 -0.3000  1.0000   5.00   100  0.0500  0.00   
4      0.010201  0.0190  0.6100 -0.7000  6.2100   1.00   100  0.0319  0.00   
5      0.090000  0.0900  1.0000 -0.3000  2.0000   5.00   100  0.0500  0.00   
6      0.160000  0.1600  2.0000 -0.8000  1.0000  10.00     1  0.0000  0.00   
7      0.019400  0.0586  0.5196 -0.6747  1.0407   4.00   100  0.0000  0.00   
8      0.040000  0.2500  1.0000 -0.5000  4.0000   1.00   100  0.0100  0.02   
9      0.010000  0.2500  1.0000 -0.5000  4.0000   0.01   100  0.0100  0.02   
10     0.114000  0.0430  1.0000 -0.3600  2.5800   1.00   100  0.0000  0.00   
11     0.090000  0.0900  0.4000  0.0000  4.0000   0.50   100  0.0000  0.00   
12     0.122500  0.1225  0.8000  0.0000  8.0000   0.50   100  0.0000  0.00   

             df        nc col_name  \
Sheet                                
1      0.080000  0.000271    Price   
2      0.059259  0.000333    Price   
3      0.360000  0.001221    Price   
4      1.268369  0.000686    Price   
5      0.720000  0.000016    Price   
6      0.160000  0.000004    Price   
7      0.903535  0.002365    Price   
8      4.000000  0.005970    Price   
9      4.000000  1.960267    Price   
10     0.443760  0.048228    Price   
11     9.000000  0.704329    Exact   
12     6.125000  0.057138    Exact   

                                               Reference  
Sheet                                                     
1      Table 2 (Case I) in Andersen (2008), Table 2, ...  
2      Table 3 (Case II) in Andersen (2008), Table 2,...  
3      Table 2, 4  (Case II) in Van Haastrecht & Pels...  
4      Tables 1, 4 in Broadie & Kaya (2006). Case 4 i...  
5      Tables 2, 5 in Broadie & Kaya (2006), SV-I in ...  
6           Figure 6 in Kahl and Jäckel (2005, Wilmott).  
7               Smith (2007), Case 6 in Tse & Wan (2013)  
8      Lewis (2019) https://financepress.com/2019/02/...  
9      Lewis (2019) https://financepress.com/2019/02/...  
10     Table A3, Figure 3 (Set I) in von Sydow et al....  
11                        Table 1A in Ball & Roma (1994)  
12                        Table 1B in Ball & Roma (1994)

## Table 1A

In [4]:
sheet_no = 11
m, p, rv = pf.HestonFft.init_benchmark(sheet_no)
m0, *_ = pf.HestonUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike      BS     OP2     OP3   Exact
0      80  21.425  21.430  21.426  21.430
1      90  13.990  13.933  13.937  13.935
2     100   8.447   8.357   8.367   8.359
3     110   4.746   4.677   4.683   4.680
4     120   2.504   2.485   2.483   2.487

In [5]:
### Difference in Exact price
np.round(m.price(**rv['args_pricing']), 3) - p['Exact'].values

array([0., 0., 0., 0., 0.])

In [6]:
### Difference in OP2 price
np.round(m0.price(**rv['args_pricing']), 3) - p['OP2'].values

array([0., 0., 0., 0., 0.])

## Table 1B

In [7]:
sheet_no = 12
m, p, rv = pf.HestonFft.init_benchmark(sheet_no)
m0, *_ = pf.HestonUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike      BS     OP2     OP3   Exact
0      80  22.206  22.190  22.186  22.192
1      90  15.186  15.094  15.105  15.099
2     100   9.848   9.719   9.738   9.726
3     110   6.093   5.986   6.000   5.992
4     120   3.623   3.573   3.573   3.576

In [8]:
### Difference in Exact price
np.round(m.price(**rv['args_pricing']), 3) - p['Exact'].values

array([0., 0., 0., 0., 0.])

In [9]:
### Difference in OP2 price
np.round(m0.price(**rv['args_pricing']), 3) - p['OP2'].values

array([0.001, 0.   , 0.   , 0.   , 0.   ])