In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as spst

#import sys
#sys.path.insert(sys.path.index('')+1, 'D:/Github/pyfeng')
import pyfeng as pf

np.set_printoptions(precision=3)

# OUSV Model by Schobel & Zhu (1999)

Schöbel R, Zhu J (1999) Stochastic Volatility With an Ornstein–Uhlenbeck Process: An Extension. Rev Financ 3:23–46. https://doi.org/10.1023/A:1009803506170

In [3]:
pf.OusvFft.init_benchmark()

sigma  theta  vov  rho  mr  texp  spot     intr col_name  \
Sheet                                                             
1       0.20   0.20  0.1 -0.7   4   1.0   100  0.09531    Price   
2       0.20   0.20  0.1 -0.7   4   5.0   100  0.09531    Price   
3       0.20   0.20  0.1 -0.7   4  10.0   100  0.09531    Price   
4       0.25   0.25  0.3 -0.6   8   1.0   100  0.09531    Price   
5       0.20   0.20  0.1  0.0   4   0.5   100  0.09530    Price   
6       0.20   0.10  0.1  0.0   4   0.5   100  0.09530    Price   
7       0.20   0.30  0.1  0.0   4   0.5   100  0.09530    Price   
8       0.15   0.00  0.1  0.5   4   0.5   100  0.09530    Price   
9       0.15   0.00  0.1  0.0   4   0.5   100  0.09530    Price   
10      0.15   0.00  0.1 -0.5   4   0.5   100  0.09530    Price   

                                Reference  
Sheet                                      
1             Table 2 in Li and Wu (2019)  
2             Table 2 in Li and Wu (2019)  
3             Table 2 in Li and Wu (2019)  
4             Table 3 in Li and Wu (2019)  
5        Table 1A in Schobel & Zhu (1999)  
6        Table 1B in Schobel & Zhu (1999)  
7        Table 1C in Schobel & Zhu (1999)  
8        Table 2E in Schobel & Zhu (1999)  
9      Table 2D/F in Schobel & Zhu (1999)  
10       Table 2G in Schobel & Zhu (1999)

## Table 1A

In [4]:
sheet_no = 5
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
m0, *_ = pf.OusvUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike   Price    AVBS    SSBS      -1   -0.75    -0.5   -0.25       0  \
0      90  15.155  15.152  15.118  15.416  15.355  15.292  15.225  15.155   
1      95  11.379  11.391  11.342  11.617  11.562  11.503  11.443  11.379   
2     100   8.176   8.203   8.142   8.307   8.275   8.243   8.210   8.176   
3     105   5.617   5.650   5.584   5.576   5.585   5.595   5.606   5.617   
4     110   3.694   3.722   3.658   3.468   3.525   3.582   3.638   3.694   
5     115   2.333   2.349   2.293   1.966   2.063   2.156   2.246   2.333   
6     120   1.420   1.422   1.377   0.995   1.110   1.218   1.321   1.420   

     0.25     0.5    0.75       1  
0  15.081  15.003  14.919  14.828  
1  11.313  11.243  11.169  11.092  
2   8.141   8.106   8.070   8.034  
3   5.628   5.640   5.652   5.665  
4   3.749   3.803   3.856   3.909  
5   2.416   2.497   2.576   2.653  
6   1.514   1.605   1.693   1.777

In [5]:
rhos = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]

for rho in rhos:
    m.rho = rho
    print(np.round(m.price(**rv['args_pricing']), 3) - p[rho].values)

[-0.001  0.     0.     0.     0.     0.     0.   ]
[ 0.    -0.001  0.     0.     0.     0.     0.   ]
[-0.001  0.     0.     0.     0.     0.     0.   ]
[ 0.    -0.001  0.     0.     0.     0.     0.   ]
[0. 0. 0. 0. 0. 0. 0.]
[ 0.    -0.001  0.     0.     0.     0.     0.   ]
[ 0.    -0.001  0.     0.     0.     0.     0.   ]
[-0.001  0.     0.     0.     0.     0.     0.   ]
[ 0.    -0.001  0.     0.     0.     0.     0.   ]


In [6]:
### AVBS price
np.round(m0.price(**rv['args_pricing']), 3) - p['AVBS'].values

array([0., 0., 0., 0., 0., 0., 0.])

## Table 1B

In [7]:
sheet_no = 6
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
m0, *_ = pf.OusvUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike   Price    AVBS      -1   -0.75    -0.5   -0.25       0    0.25  \
0      90  14.515  14.501  14.730  14.679  14.626  14.572  14.515  14.456   
1      95  10.346  10.348  10.600  10.541  10.480  10.415  10.346  10.271   
2     100   6.803   6.829   6.976   6.936   6.894   6.849   6.803   6.753   
3     105   4.093   4.132   4.057   4.066   4.075   4.085   4.093   4.102   
4     110   2.254   2.282   1.977   2.051   2.121   2.189   2.254   2.316   
5     115   1.144   1.150   0.739   0.853   0.957   1.053   1.144   1.230   
6     120   0.542   0.530   0.179   0.279   0.371   0.458   0.542   0.621   

      0.5    0.75       1  
0  14.395  14.330  14.261  
1  10.191  10.103  10.005  
2   6.701   6.645   6.587  
3   4.110   4.117   4.125  
4   2.376   2.433   2.489  
5   1.311   1.389   1.463  
6   0.698   0.773   0.845

In [8]:
rhos = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]

for rho in rhos:
    m.rho = rho
    print(np.round(m.price(**rv['args_pricing']), 3) - p[rho].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


In [9]:
### AVBS price
np.round(m0.price(**rv['args_pricing']), 3) - p['AVBS'].values

array([0., 0., 0., 0., 0., 0., 0.])

## Table 1C

In [10]:
sheet_no = 7
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
m0, *_ = pf.OusvUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike   Price    AVBS      -1   -0.75    -0.5   -0.25       0    0.25  \
0      90  16.106  16.111  16.357  16.298  16.236  16.172  16.106  16.037   
1      95  12.651  12.666  12.846  12.800  12.751  12.702  12.651  12.598   
2     100   9.687   9.711   9.777   9.755   9.732   9.710   9.687   9.665   
3     105   7.237   7.264   7.186   7.198   7.210   7.223   7.237   7.251   
4     110   5.279   5.305   5.084   5.133   5.182   5.230   5.279   5.328   
5     115   3.768   3.786   3.449   3.531   3.611   3.690   3.768   3.844   
6     120   2.635   2.646   2.235   2.340   2.441   2.540   2.635   2.728   

      0.5    0.75       1  
0  15.964  15.889  15.810  
1  12.544  12.489  12.432  
2   9.642   9.620   9.598  
3   7.265   7.280   7.296  
4   5.377   5.426   5.475  
5   3.919   3.993   4.065  
6   2.819   2.908   2.994

In [11]:
rhos = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]

for rho in rhos:
    m.rho = rho
    print(np.round(m.price(**rv['args_pricing']), 3) - p[rho].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


In [12]:
### AVBS price
np.round(m0.price(**rv['args_pricing']), 3) - p['AVBS'].values

array([0., 0., 0., 0., 0., 0., 0.])

## Table 2E

In [13]:
sheet_no = 9
m, p, rv = pf.OusvUncorrBallRoma1994.init_benchmark(sheet_no)
p

Strike   Price       0     0.1     0.2     0.3  AVBS-0  AVBS-0.1  AVBS-0.2  \
0      90  14.200  14.200  14.351  14.871  15.754  14.194    14.333    14.864   
1      95   9.527   9.527   9.997  10.952  12.198   9.510     9.990    10.962   
2     100   5.269   5.269   6.254   7.632   9.161   5.277     6.282     7.662   
3     105   2.170   2.170   3.451   5.022   6.676   2.213     3.499     5.060   
4     110   0.645   0.645   1.679   3.124   4.727   0.654     1.708     3.155   
5     115   0.150   0.150   0.731   1.845   3.259   0.132     0.728     1.859   
6     120   0.030   0.030   0.292   1.040   2.192   0.018     0.272     1.037   

   AVBS-0.3  
0    15.757  
1    12.213  
2     9.187  
3     6.707  
4     4.755  
5     3.278  
6     2.200

In [14]:
thetas = [0, 0.1, 0.2, 0.3]

for theta in thetas:
    m.theta = theta
    print(np.round(m.price(**rv['args_pricing']), 3) - p[f'AVBS-{theta}'].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


## Table 2E

In [15]:
sheet_no = 8
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
p

Strike   Price       0     0.1     0.2     0.3
0      90  14.189  14.189  14.262  14.723  15.608
1      95   9.459   9.459   9.842  10.804  12.082
2     100   5.141   5.141   6.132   7.551   9.109
3     105   2.173   2.173   3.466   5.044   6.703
4     110   0.763   0.763   1.812   3.239   4.828
5     115   0.244   0.244   0.895   2.014   3.414
6     120   0.075   0.075   0.425   1.220   2.376

In [16]:
thetas = [0, 0.1, 0.2, 0.3]

for theta in thetas:
    m.theta = theta
    print(np.round(m.price(**rv['args_pricing']), 3) - p[theta].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


## Table 2F

In [17]:
sheet_no = 9
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
p.iloc[:,:6]

Strike   Price       0     0.1     0.2     0.3
0      90  14.200  14.200  14.351  14.871  15.754
1      95   9.527   9.527   9.997  10.952  12.198
2     100   5.269   5.269   6.254   7.632   9.161
3     105   2.170   2.170   3.451   5.022   6.676
4     110   0.645   0.645   1.679   3.124   4.727
5     115   0.150   0.150   0.731   1.845   3.259
6     120   0.030   0.030   0.292   1.040   2.192

In [18]:
thetas = [0, 0.1, 0.2, 0.3]

for theta in thetas:
    m.theta = theta
    print(np.round(m.price(**rv['args_pricing']), 3) - p[theta].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


## Table 2G

In [19]:
sheet_no = 10
m, p, rv = pf.OusvFft.init_benchmark(sheet_no)
p

Strike   Price       0     0.1     0.2     0.3
0      90  14.225  14.225  14.441  15.003  15.887
1      95   9.600   9.600  10.130  11.084  12.306
2     100   5.372   5.372   6.361   7.710   9.213
3     105   2.152   2.152   3.435   5.003   6.652
4     110   0.504   0.504   1.529   3.004   4.626
5     115   0.061   0.061   0.545   1.660   3.097
6     120   0.004   0.004   0.155   0.842   1.995

In [20]:
thetas = [0, 0.1, 0.2, 0.3]

for theta in thetas:
    m.theta = theta
    print(np.round(m.price(**rv['args_pricing']), 3) - p[theta].values)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
